### ISSUE TITLE
Windows Build Issue due to OpenSSL Library Name Change

### ISSUE THREAD

**Issue by jvmahon** [dazoe/ed25519#18]
In Windows, you get an install error if you are installing on a system with OpenSSL Version 1.1 or later installed.  The problem is that OpenSSL has changed the name of a library file. I believe this can be fixed in the bindings.gyp file by changing line 88 
from:
			'-l<(openssl_root)/lib/libeay32.lib',
to:
			'-l<(openssl_root)/lib/libcrypto.lib',
Or perhaps by having a test to check which of these libraries (if any) are installed and then select the installed one.

Is it necessary to even explicitly include this library? ed25519 seems to compile / install even if this is commented out.

**Comment by ldjking** [comment]
Did you build successully? I hava tried sevral weeks!  

错误	LNK2019	无法解析的外部符号 "__declspec(dllimport) public: static class v8::Local<class v8::FunctionTemplate> __cdecl v8::FunctionTemplate::New(class v8::Isolate *,void (__cdecl*)(class v8::FunctionCallbackInfo<class v8::Value> const &),class v8::Local<class v8::Value>,class v8::Local<class v8::Signature>,int,enum v8::ConstructorBehavior)" (__imp_?New@FunctionTemplate@v8@@SA?AV?$Local@VFunctionTemplate@v8@@@2@PEAVIsolate@2@P6AXAEBV?$FunctionCallbackInfo@VValue@v8@@@2@@ZV?$Local@VValue@v8@@@2@V?$Local@VSignature@v8@@@2@HW4ConstructorBehavior@2@@Z)，该符号在函数 "public: static class v8::Local<class v8::FunctionTemplate> __cdecl Nan::imp::Factory<class v8::FunctionTemplate>::New(void (__cdecl*)(class Nan::FunctionCallbackInfo<class v8::Value> const &),class v8::Local<class v8::Value>,class v8::Local<class v8::Signature>)"

**Comment by jvmahon** [comment]
No. You must use OpenSSL 1.0 and cannot use the 1.1 versions.

**Comment by erikma** [comment]
See #20
