### ISSUE TITLE
Build error on Node 10 and OpenSSL 1.1.1a

### ISSUE THREAD

**Issue by erikma** [dazoe/ed25519#21]
Fix for #18 as well as break in Windows build under Node 10. Fixes in PR #20.

**Comment by erikma** [comment]
Build error for OpenSSL, for reference: LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib' [node_modules\ed25519\build\ed25519.vcxproj]

Build error for Node 10: node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..\src\ed25519.cc) [node_modules\ed25519\build\ed25519.vcxproj]

**Comment by gaoxiangxyz** [comment]
@erikma Maybe you should look at this [repo](https://github.com/gaoxiangxyz/ed25519) which removing dependency on openssl

**Comment by erikma** [comment]
@gaoxiangxyz thanks for the tip, I made use of it in latest https://github.com/erikma/passport-sqrl. But I found I had to force-upgrade my package-lock to "nan" version 2.13.1 to avoid the compile error below, see release notes on latest package on my README. Can you update your fork by:

- npm update (all packages), or at least "npm update nan@2.13.1" to force the correct dependency
- Update the package version in package.json to 0.0.6 to make it newer

Compile error from nan being too old:

node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSe
t': is not a member of 'v8::Object' (compiling source file ..\src\ed25519.cc) [
node_modules\ed25519\build\ed25519.vcxproj]

**Comment by gaoxiangxyz** [comment]
@erikma The update is done as you wish

**Comment by erikma** [comment]
@gaoxiangxyz Thank you! Updated to use your new commit.

**Comment by erikma** [comment]
Merged #20 to clear this old item out. Moving forward to include changes from various forks.
