### ISSUE TITLE
Add support for Node 12.0.0

### ISSUE THREAD

**Issue by RajeshkannanRamakrishnan** [dazoe/ed25519#23]
support required for node 12.
Getting an error in node 12
`../src/ed25519.cc:19:89: error: no matching member function for call to
      'ToObject'
  ...(!Buffer::HasInstance(info[0])) || (Buffer::Length(info[0]->ToObject()) ...
                                                        ~~~~~~~~~^~~~~~~~
/Users/<username>/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2576:44: note: 
      candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
`

**Comment by palasinio** [comment]
Has someone found an Node ed25519 implementation building with node 12?

**Comment by palasinio** [comment]
You can find a later fork here:
https://github.com/pokt-network/ed25519

**Comment by RajeshkannanRamakrishnan** [comment]
> You can find a later fork here:
> https://github.com/pokt-network/ed25519
test cases are failing

**Comment by p3root** [comment]
Same issue with node14 on windows and debian! I guess it's the same issue! 

`error C2660: 'v8::Value::ToObject': function does not take 0 arguments [C:\dev\saiive\saiive\src\saiive.mo
bile\saiive\node_modules\ed25519\build\ed25519.vcxproj]`

**Comment by erikma** [comment]
See https://github.com/gaoxiangxyz/ed25519/pull/2 for another diff for Node 12.

**Comment by erikma** [comment]
Merged the changes from https://github.com/gaoxiangxyz/ed25519/pull/2 into master to convert to Node 12's API changes. I'll update the published package when I have permissions.
