### ISSUE TITLE
Windows NodeJS x86: ed25519.cc(78): error C2466: cannot allocate an array of constant size 0

### ISSUE THREAD

**Issue by nzhome** [dazoe/ed25519#5]
ed25519.cc
..\src\ed25519.cc(78): error C2057: expected constant expression [C:\Program Files (x86)\nodejs\node_modules\homebridge\node_modules\HAP-NodeJS\node_modules\ed25519\build\ed25519.vcxproj]
..\src\ed25519.cc(78): error C2466: cannot allocate an array of constant size 0 [C:\Program Files (x86)\nodejs\node_modules\homebridge\node_modules\HAP-NodeJS\node_modules\ed25519\build\ed25519.vcxproj]
..\src\ed25519.cc(78): error C2133: 'signatureMessageData' : unknown size [C:\Program Files (x86)\nodejs\node_modules\homebridge\node_modules\HAP-NodeJS\node_modules\ed25519\build\ed25519.vcxproj]
..\src\ed25519\sc_reduce.c(274): warning C4244: '=' : conversion from 'crypto_int64' to 'unsigned char', possible loss of data [C:\Program Files (x86)\nodejs\node_modules\homebridge\node_modules\HAP-NodeJS\node_modules\ed25519\build\ed25519.vcxproj]

Line77 unsigned long long sigLen = 64 + messageLen;
Line78 unsigned char signatureMessageData[sigLen];
Line79 crypto_sign(signatureMessageData, &sigLen, messageData, messageLen, privateKey);

**Comment by akaustel** [comment]
Did you get this problem fixed? I'm working on Linux mainly, but would really like the thing to work on Windows as well. Shouldn't this memory be allocated with `malloc`?

**Comment by akaustel** [comment]
I fixed the problems by allocating a Buffer and fixing the binding.gyp to find OpenSSL which is used for SHA512 (https://github.com/akaustel/ed25519/commit/82fae8e76e88a05eca5df4ae1423c597d1661307). It would seem you fixed it yourself too? Any response from @dazoe? Going to publish the fix?

**Comment by dazoe** [comment]
I'm not much of a c / c++ programmer, and haven't been using node.js for a long time. I looked through  everyone's forks and there seems to be two different methods to correct this. One using malloc/free and the other is using a node buffer. I think the best approach is to use malloc/free.
Did you try dennis-bt's fork? I'm thinking about pulling in changes from him.

**Comment by akaustel** [comment]
That seems like a good idea. I found one more problem which I fixed, which is the bindings.gyp target and the module names should match, i.e. `native` should be changed to `ed25519` in `src/ed25519.cc`: `NODE_MODULE(ed25519, InitModule)`. I did not see this fix in dennis-bt's fork.

**Comment by dazoe** [comment]
Pulled in changes from denis-bt and changed module name. Could you double check this works on windows? I don't have a windows machine set up.

**Comment by akaustel** [comment]
Sure. Just pulled the changes and executed the `example.js`:

```sh
  Generating code
  Finished generating code
  ed25519.vcxproj -> C:\Users\redacted\Documents\work\ed2fix\ed25519\build\Release\\ed25519.node
bindings@1.2.1 node_modules\bindings

nan@1.9.0 node_modules\nan

C:\Users\redacted\Documents\work\ed2fix\ed25519>node example.js
Signature valid
Signature2 valid
Signature3 valid

C:\Users\redacted\Documents\work\ed2fix\ed25519>
```

Seems to work!

**Comment by nzhome** [comment]
PERFECT!  it works, it works.. thank you.

**Comment by akaustel** [comment]
Are you going to make a release, @dazoe?

**Comment by dazoe** [comment]
I am not the owner of the package on npm, I have sent an email to stellar asking for access to it so i can publish. Or they can update it them selves which ever.

**Comment by nzhome** [comment]
just update your package.json  to pull from here directly anyhow..  for example....

  "dependencies": {
    "curve25519": "git://github.com/thejh/node-curve25519",
    "debug": "^2.2.0",
    "ed25519": "git://github.com/dazoe/ed25519",

**Comment by akaustel** [comment]
Ok, @KenanSulayman, never tried that before, but seems to work! Just feels neater with specific released versions.
